<h3>Lab 7</h3>

# Feel the Heat! Part 1

<div>
    <img src="temperature-anomolies.gif" width=700><br>
</div>

<small>Source: [110 Years of Australian Temperatures](http://www.bom.gov.au/climate/history/temperature/), Bureau of Meteorology</small>


We might *[love a sunburnt country](https://en.wikipedia.org/wiki/My_Country#/media/File:My_Country_part_1.jpg)*, but Dorothea Mackellar in 1908 couldn't have envisioned quite how sunburnt its getting!

The 2019 temperature anomolies map (shown above) paints another alarming picture! Of course, this is just one year, and we are interested in trends.

In this lab, we will again examine raw data from the Bureau of Meteorology. This time we will focus on maximum temperatures for Western Australian towns, from the north to the south.

This lab also provides practice working with **2-dimensional arrays**.


## Data Acquisition and Inspection

Once again we will source our data from the Australian Government's **Bureau of Meteorology (BOM)** *Climate Data Online* service.

* Find the _monthly average maximum temperature_ data.
* Find and download the historical data for:
  * Perth Airport
  * Geraldton Town
  * Albany
  * Broome Airport

* Have a look at the data. Read one of the `Note.txt` files so that you can see what is in each file, and the structure.
* Inspect one of each type of data file to see that they conform to your expectations from reading the Note.

The temperature data is _time series data_ so of course changes over time. For this lab, you have been provided with a snapshot of this data (with suffix `_20`) so that we are all using the same set of data, and I can give examples of the output you should expect.

You may upload the latest data to your CoCalc project for extra examples if you wish, taking care of course not to overwrite the provided data. The folders for each town should not be more than about 60KB each.


#### Set up

We will set up our constants as follows.

- In this lab we will use the second kind of file discussed in `Note.txt` (12 months per line).

- We will use a dictionary to map town names to the station codes. This will allow us to easily find the data for each town.

- For simplicity we will only use one "product" (monthly maximum temperatures), however you can see that we could easily generalise this to other data sets (products) in a similar way to the stations.

In [2]:
MONTHLY_TEMPERATURE = "IDCJAC0002"
PER_LINE = 12

STATIONS = {"Albany": "009500",
            "Perth": "009021",
            "Broome": "003003",
            "Geraldton": "008050"
           }

## File paths

#### Using `format()`
First, lets use the `format()` function to recreate a directory name and a filename. We'll use Albany as an example.

If you have note used string formatting before, have a look at the documentation for `format()` at: https://docs.python.org/3.8/library/string.html#format-string-syntax. If you are not familiar with specification languages (you are not expected to be) it is better to look at the examples further down that page.

(You should use the the "new" `{}` formatting, not the "old" `%` formatting.)

For example, to generate the directory name we could use:
```
albany_dir_name = "{}_{}".format(MONTHLY_TEMPERATURE, STATIONS["Albany"])
```

* Try this and check the output.
* Use `format()` with the above constants to generate the file name for the 12 months per line mean maximum temperature data for Albany.


In [3]:
albany_dir_name = "{}_{}".format(MONTHLY_TEMPERATURE, STATIONS["Albany"])
print(albany_dir_name)
albany_file = "{}_{}_Data{}.csv".format (MONTHLY_TEMPERATURE, STATIONS["Albany"], PER_LINE)
print(albany_file)

IDCJAC0002_009500
IDCJAC0002_009500_Data12.csv


#### Using `pathlib`

So far we have just used strings for filenames. When extracting data from a filesystem, however, it is much cleaner to use _objects_ representing file paths. The `pathlib` library is excellent for this. 

Have a look at the [pathlib documentation](https://docs.python.org/3/library/pathlib.html). We will use some basic pathlib utilities here, but you can see that switching from simple strings to pathlib objects provides a lot more utility.

Let's start by checking our "current working directory" (or "folder").

* Execute the following code.
```
from pathlib import Path
print(Path.cwd())
Path.cwd()
```
* Go to the "folder" icon in the tabs bar, and open a new linux terminal. Type `pwd` ("print working directory") at the terminal prompt. 
* In python execute:
```
!pwd
```
How to they compare?


In [4]:
from pathlib import Path
print(Path.cwd())
Path.cwd()

/home/user/Labs/Heat1


PosixPath('/home/user/Labs/Heat1')

In [5]:
!pwd

/home/user/Labs/Heat1


pathlib defines the forward slash `/` as a convenient operator for building paths in a Unix-like way.

Let's use pathlib to examine the directory for the previous lab. Try:
```
rainfall = Path.home()/"Labs"/"Rainfall"
print(rainfall)
print(rainfall.is_dir(),"\n")
for file_path in rainfall.iterdir():
    print(file_path)
for file_path in rainfall.iterdir():
    print(file_path.name)
```
The first line uses the shorthand `/` operator to create a new path object. The third line confirms that this is the path of a directory. Notice that the iterator returns path objects. To find the name of the file at that path, we look at the attribute `name`.

In [6]:
rainfall = Path.home()/"Labs"/"Rainfall"
print(rainfall)
print(rainfall.is_dir(),"\n")
for file_path in rainfall.iterdir():
    print(file_path)
for file_path in rainfall.iterdir():
    print(file_path.name)

/home/user/Labs/Rainfall
True 

/home/user/Labs/Rainfall/airport2021.png
/home/user/Labs/Rainfall/DUE_DATE.txt
/home/user/Labs/Rainfall/Rainfall.ipynb
/home/user/Labs/Rainfall/squares.png
/home/user/Labs/Rainfall/rainfall-deciles.png
/home/user/Labs/Rainfall/IDCJAC0001_009025_Data1.csv
/home/user/Labs/Rainfall/IDCJAC0001_009021_Data1.csv
/home/user/Labs/Rainfall/airport50-60.png
/home/user/Labs/Rainfall/.Rainfall.ipynb.sage-jupyter2
airport2021.png
DUE_DATE.txt
Rainfall.ipynb
squares.png
rainfall-deciles.png
IDCJAC0001_009025_Data1.csv
IDCJAC0001_009021_Data1.csv
airport50-60.png
.Rainfall.ipynb.sage-jupyter2


* Create a path object from `albany_dir_name` and use this to list the contents of the Albany directory.
* Using this directory path, create a path to the 12 months per line data file for Albany.
* Check that the file exists. This is a good way of double checking that you generated the path correctly.

_(Hint: Look at the documentation.)_

* Check the file size.
* Read in the contents of the file, print the first 100 characters, and check it is what you expect.
* Give thanks to John McCarthy (LISP) and Alan Kay (Smalltalk)!


In [7]:
file_name = "{}_{}_{}".format(MONTHLY_TEMPERATURE, STATIONS["Albany"],"Data12.csv")
p = Path.home()/"Labs"/"Heat1"/albany_dir_name/file_name
p
p.exists()
p.stat().st_size

with open(p,"r") as myfile:
    file_content = myfile.read()
    print(file_content[:100])

#for file_path in p.iterdir():
    #print(file_path.name)

Product code,Station Number,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Annual
IDCJAC0002,0


In [8]:
albany_dir = Path(albany_dir_name) #no need do cwd as it will be default relative to where this is running from (CWD)
print(albany_dir)
for file in albany_dir.iterdir():
    print(file)
albany_path = albany_dir / albany_file
print(albany_path.exists())
print(albany_path.stat().st_size)
print(albany_path.read_text()[:100])

IDCJAC0002_009500
IDCJAC0002_009500/IDCJAC0002_009500_Data12.csv
IDCJAC0002_009500/IDCJAC0002_009500_Data1.csv
IDCJAC0002_009500/IDCJAC0002_009500_Note.txt
True
9612
Product code,Station Number,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Annual
IDCJAC0002,0


#### Q1. Putting it together [1 lab mark]

* Write a "helper" function `temperature_file(town)` that takes the name of a town (as defined in STATIONS) and returns a path to the data file.

For example:

```
temperature_file("Albany")

PosixPath('IDCJAC0002_009500/IDCJAC0002_009500_Data12.csv')
```


In [9]:
def temperature_file (town):
    dir_name = "{}_{}".format(MONTHLY_TEMPERATURE, STATIONS[town])
    
    file_name = "{}_{}_{}".format(MONTHLY_TEMPERATURE, STATIONS[town],"Data12.csv")
    
    p = Path(dir_name)/file_name
    
    return p
    



In [10]:
from nose.tools import assert_equal
broome_file = temperature_file("Broome")
import pathlib
assert_equal(type(broome_file), pathlib.PosixPath)
assert_equal(str(broome_file), "IDCJAC0002_003003/IDCJAC0002_003003_Data12.csv")
assert_equal(broome_file.is_file(), True)
print("So far, so good.")


So far, so good.


### Missing values, NaN, and np.nan

In python, we can use `None` for missing items, for example in a list. Try:
```
alist = ['a',1, None, ['b']]
[type(item) for item in alist]
```
But what if we want to represent missing data in an array?

We know that arrays are homogenous. `None` is of type `NoneType`, so it can't be included in an array of numbers. What happens if we try?
```
anarray = np.array([0.0, None], dtype=float)
anarray.dtype
```
It appears to have worked. But let's take a closer look:
```anarray

array([ 0., nan])
```

To keep the compatible type (`float64`), numpy has replaced `None` with `np.nan` (or `np.NaN`), or _not-a-number_. `nan` is  a special float defined for this purpose, long before python came along, by [IEEE 754](https://numpy.org/doc/stable/user/misc.html).

One thing to bear in mind about NaN's is they are not equal to other NaN's:
```
a = np.nan
b = np.nan
a == b

False
```

So when testing for `np.nan`, always use `np.isnan()`:
```
a = np.nan
b = np.nan
np.isnan(a) and np.isnan(b)

True
```


In [11]:
alist = ['a',1, None, ['b']]
[type(item) for item in alist]

[str, int, NoneType, list]

In [12]:
import numpy as np

In [13]:
anarray = np.array([0.0, None], dtype=float)
anarray.dtype

[item.dtype for item in anarray]

[dtype('float64'), dtype('float64')]

In [14]:
#np.array([ 0., nan])

In [15]:
a = np.nan
b = np.nan
a == b


False

In [16]:
a = np.nan
b = np.nan
np.isnan(a) and np.isnan(b)

True

## Putting the data in a 2-D array, using `np.genfromtxt`

In the last lab we used the `csv` package for parsing text files. While `csv` is particularly targeted at reading csv (-like) files, a range of other libraries include their own bespoke file/buffer/string parsers.

For example, `numpy` has `fromstring`, `loadtxt` and the more general `genfromtxt` (as well as others for different file/buffer types).

`genfromtxt` is extremely versatile - for example, it allows us to skip rows, select columns and deal with missing values.

Have a closer inspection of one of our 12 month per line data files. They have:
 * a header row, that we won't need for analysis
 * 16 columns, but not all of them are needed
 * missing values, represented by the string "null"

This makes `genfromtxt` a great choice, because we can skip some cleaning work by reading just what we need.

* Read the API for `genfromtxt` in the latest version of the numpy manual.
* Read the data for Albany into an array `albany` (1 line of code). Your array should:
  * exclude the header line
  * exclude the first two columns (code and station number)
  * ensure any occurrences of "null" are replaced with `nan`

```
print(albany[-4:])

[[2017.    22.1   22.2   21.8   20.1   19.4   19.    15.9   16.7   17.5
    19.1   20.6   21.5   19.7]
 [2018.    22.4   23.    22.4   21.2   20.7   17.4   17.    16.2   17.
    19.    18.7   21.1   19.7]
 [2019.    22.2   22.2   21.2   21.2   18.7   17.6   16.8   17.9   19.3
    19.3   19.4   23.5   19.9]
 [2020.    22.2   23.4   23.1   21.2   19.6   18.9   17.3    nan    nan
     nan    nan    nan    nan]]
```

Note that `gefromtxt()` will accept a `pathlib` `Path`, and you should use this rather than strings.

The the resulting array should be of type float64. This should happen by default, you don't need to specify it - but you should check it (see `np.dtype`). As we know the array is homogeneous, so this includes the years, and the missing values.

* Consult the [array attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes) documentation, and print the _shape_ of the albany array, the _number of dimensions_, and its _dtype_.

In [17]:
albany_path = temperature_file ("Albany")
albany_path
albany = np.genfromtxt(albany_path,delimiter=",",skip_header = 1, filling_values=np.nan,usecols = (np.arange(2,16)))
albany[:3]
albany[-4:]

# missing_values = ["null"]

array([[2019. ,   22.2,   22.2,   21.2,   21.2,   18.7,   17.6,   16.8,
          17.9,   19.3,   19.3,   19.4,   23.5,   19.9],
       [2020. ,   22.2,   23.4,   23.1,   21.2,   19.6,   18.9,   17.3,
          16.9,   18.1,   19.4,   20.5,   21.1,   20.1],
       [2021. ,   22.8,   21.9,   23.6,   21.1,   19.7,   17.5,   16. ,
          17.2,   18.1,   18. ,   18.8,   21.3,   19.7],
       [2022. ,   22.4,   23.6,   22.6,   21.4,   19. ,   17.6,   17.2,
          15.9,    nan,    nan,    nan,    nan,    nan]])

In [18]:
albany.dtype

dtype('float64')

In [19]:
np.shape(albany) 

(107, 14)

In [20]:
albany.ndim

2

#### Selecting items in 2-d arrays

We know how to select an item in a 1-d array using a slice. To select an item in a 2-d array, we just select the row and the column.

For example, `albany[0,-1]` will select the item in the last (-1 th) column of the first (zeroth) row, that is, the annual average temperature for 1880.

* Print out the annual average temperature for the last year in the table (1 line of code).
* Print out the annual average temperature for the second last year in the table.


In [21]:
albany[-1,-1]

nan

In [22]:
albany[-2,-1]

19.7

In [23]:
albany[:5,-4:-1]

array([[16.2, 18. , 20.8],
       [16.1, 18.7, 20.7],
       [17.3, 17.8, 20.8],
       [16.5, 18.2, 21.9],
       [17.3, 19.5, 18.7]])

In [24]:
albany

array([[1880. ,   22.1,   22.8, ...,   18. ,   20.8,   18.2],
       [1881. ,   20.1,   22.2, ...,   18.7,   20.7,   18.2],
       [1882. ,   20.2,   22.1, ...,   17.8,   20.8,   17.8],
       ...,
       [2020. ,   22.2,   23.4, ...,   20.5,   21.1,   20.1],
       [2021. ,   22.8,   21.9, ...,   18.8,   21.3,   19.7],
       [2022. ,   22.4,   23.6, ...,    nan,    nan,    nan]])

In [25]:
albany [[2,3,4],[3,4,5]]

array([20.1, 20.1, 16.6])

#### Q2. Inspecting the year range for a town [1 lab mark]

* Write a function `year_range(town)` that returns a pair of integers representing the first year and the last year included in that town's table (you may assume the tables are always in the correct format and in chronological order).

You should use `genfromtxt` to read the data, and then use array selection (no loops). This should only take a couple of lines of code!

Check your answers for the various towns are correct.

In [26]:
def year_range(town):
    path = temperature_file (town)
    text = np.genfromtxt(path,delimiter=",",skip_header = 1, filling_values=np.nan, usecols = (np.arange(2,16)))
    return int(text[0,0]),int(text[-1,0])



In [27]:
from nose.tools import assert_equal
assert_equal(year_range("Albany"), (1880, 2022))
print("So far, so good. Additional tests will be applied.")


So far, so good. Additional tests will be applied.


In [28]:
year_range("Perth")

(1944, 2022)

In [29]:
year_range("Geraldton")

(1880, 1953)

In [30]:
year_range("Broome")

(1939, 2022)

#### Collecting all the data

* Write a function `get_temps()` that, by iterating through the `STATIONS` dictionary in alphabetical order, returns:
  * a list of town names in alphabetical order
  * a list of arrays containing the corresponding tables of temperature data (including the year to the average annual temperature)

So that you can observe the progress and get a better idea of what data is there, output the town name, rows of data and first and last years for each town. For example:

```
(towns, tables) = get_temps()

Collecting data for Albany   :  107 years recorded between 1880 and 2022
Collecting data for Broome   :   84 years recorded between 1939 and 2022
Collecting data for Geraldton:   73 years recorded between 1880 and 1953
Collecting data for Perth    :   79 years recorded between 1944 and 2022
```

*Hint: use str.format() to align the data in columns.*



In [31]:
def get_temps():
    towns = sorted(list(STATIONS.keys())) #can do sorted(STATIONS) to directly get the keys()
    max_length = max([len(x) for x in towns])
    tables = []
    for station in towns:
        path = temperature_file (station)
        data = np.genfromtxt(path,delimiter=",",skip_header = 1, filling_values=np.nan, usecols = (np.arange(2,16)))
        tables.append(data)
        print('Collecting data for {town:<{width}} : {y_range:4.0f} years recorded between {first:.0f} and {last:.0f}'.format
              (town= station, first=data[0,0],last = data[-1,0], y_range = len(data),width = max_length))
    return towns,tables


In [32]:
(towns, tables) = get_temps()


#### Q3. A 'production' version [1 lab mark]

In this version the user has more control, including being able to turn the printed output on or off.

* Write a function `get_temperatures (stations, quiet=True)` with the same specification as `get_temps` except that:
  * a stations dictionary is passed to the function (rather than being 'hard wired' to STATIONS)
  * it takes one optional argument, `quiet`, that defaults to `True`. If `quiet` is False, then it should print the output as it reads in the data, allowing the user to monitor it, otherwise it reads the data in `silently' (this can be useful when called by other functions)


In [33]:
def get_temperatures (stations, quiet=True):
    towns = sorted(list(stations.keys()))
    max_length = max([len(x) for x in towns])
    tables = []
    for station in towns:
        path = temperature_file (station)
        data = np.genfromtxt(path,delimiter=",",skip_header = 1, filling_values=np.nan, usecols = (np.arange(2,16)))
        tables.append(data)
        if quiet == False: #if not quiet also works!!!
            print('Collecting data for {town:<{width}} : {y_range:4.0f} years recorded between {first:.0f} and {last:.0f}'.format
                  (town= station, first=data[0,0],last = data[-1,0], y_range = len(data),width = max_length))
    return towns,tables



In [34]:
from nose.tools import assert_equal
(towns, tables) = get_temperatures(STATIONS, quiet=True)
assert_equal(towns, ['Albany', 'Broome', 'Geraldton', 'Perth'])
geraldton = tables[towns.index("Geraldton")]
assert_equal(geraldton[0,0],1880.)
assert_equal(geraldton[1,-2],28.9)
print("So far so good.")


So far so good.


## Data Cleaning and Conversion


#### Selecting a row or column

We can use the slice operators in the usual way to refer to all the data between some bounds (optionally with stride). So to get all the years, for example, we can select _all rows_ and the _zeroth column_:

```
(towns, tables) = get_temperatures(STATIONS)
albany = tables[towns.index("Albany")]
albany[:,0]

array([1880., 1881., 1882., 1883., 1884., 1885., 1886., 1887., 1888.,
       1889., 1890., 1891., 1892., 1893., 1894., 1895., 1896., 1897.,
       1898., 1899., 1900., 1901., 1902., 1903., 1904., 1905., 1906.,
       1907., 1908., 1909., 1910., 1911., 1912., 1913., 1914., 1915.,
       1916., 1917., 1918., 1919., 1920., 1921., 1922., 1923., 1924.,
...
```

* Using Albany as an example, use array selection to return:
  * the first row of data
  * the last row of data
  * all the annual averages in the last column

* Use selection and numpy methods to find the minimum and maximum of the temperatures for the first recorded year for Albany. 

(The table actually contains the mean maximum temperatures for the months, so to be completely precise it is, for example, the minimum of the mean maximum temperatures, but we'll just refer to this as the minimum of the "temperatures".)

* Using array selection and numpy functions, find the minimum and maximum February temperatures for Albany.

_Hint: If you are not getting what you expect, take a look at `np.nanmin()` and `np.nanmax()`._


In [35]:
(towns, tables) = get_temperatures(STATIONS)
albany = tables[towns.index("Albany")]

In [36]:
albany [0,:]

array([1880. ,   22.1,   22.8,   20.6,   19.2,   17.5,   14.7,   15.1,
         15.2,   16.2,   16.2,   18. ,   20.8,   18.2])

In [37]:
albany [-1,:]

array([2022. ,   22.4,   23.6,   22.6,   21.4,   19. ,   17.6,   17.2,
         15.9,    nan,    nan,    nan,    nan,    nan])

In [38]:
albany [:,-1]

array([18.2, 18.2, 17.8, 17.8, 17.9, 17.8, 17.6, 17.3, 18.4, 17.1, 17. ,
       18.3, 18.8, 18.9, 19.8, 19.6, 20.1, 19.6, 20.1, 19.7, 19. , 19.8,
       19.4, 18.8, 19.7, 18.9, 19.7, 20.1, 19.7, 20. , 20.2, 20. , 19.9,
       19.5, 19.8, 20. , 20. , 19.5, 20.8, 20.3, 20.6, 21. , 19.9, 20. ,
       20. , 19.5, 19.2, 19.4, 19.3, 18.9, 20.4, 19.3, 19.8, 20.3, 20.3,
       19.4, 19.8, 20. ,  nan, 19.9, 20.4, 20. , 19.6, 19.1, 19.6, 19.7,
       19.5, 19.4, 19.9, 20.1, 20. , 19.3, 19.3, 19.4, 19.7, 19. , 19.3,
       20.2, 19.8, 20.1, 18.8, 20.3, 20.1, 20.1, 19.1,  nan,  nan, 19.8,
       19.6, 19.4, 19.6, 19.7, 19.5, 19.6, 19.8, 20.4, 20.8, 20.3, 20.3,
       20.3, 19.4, 19.7, 19.7, 19.9, 20.1, 19.7,  nan])

In [39]:
np.nanmin(albany [0,1:-1])

14.7

In [40]:
np.nanmax(albany [0,1:-1])

22.8

In [41]:
np.nanmin(albany [:,2])

19.8

In [42]:
np.nanmax(albany [:,2])

26.4

#### Selecting an area

* Use a slice to select the _first 4 months_ of data for the _first 3 years_ recorded.

Your code should be of the form:

&nbsp;&nbsp;`albany[`*select the 3 rows here*`,` *select the 4 columns here*`]`.

Check against the original csv file to ensure you have selected the correct data.

In [43]:
albany [:3,1:5]

array([[22.1, 22.8, 20.6, 19.2],
       [20.1, 22.2, 22.2, 19.6],
       [20.2, 22.1, 20.1, 18.8]])

In [46]:
albany[::10, 1:5]

array([[22.1, 22.8, 20.6, 19.2],
       [20.6, 20.8, 19.9, 19. ],
       [21.8, 23.8, 20.7, 19.1],
       [24.1, 25.2, 24.3, 23.8],
       [25.3, 24.2, 23.8, 22.8],
       [23.5, 23. , 22.7, 21.8],
       [23.3, 24.9, 23.6, 21.1],
       [23.4, 23.5, 23.3, 23.1],
       [21.8, 22.8, 20.7, 18.5],
       [20.5, 21.7, 21.9, 18.6],
       [22.7, 23.4, 22.6, 20.6]])

#### Two ways to skin a cat? (Avoiding a potential pitfall)

* Use selection to print the temperature for January 1882 (`albany[2,1]`).
* Now use selection to extract the row for 1882, then use selection on the result to extract the January reading (`albany[2][1])`.

What do you notice?

In [105]:
albany[2,1]

20.2

In [106]:
albany[2][1]

20.2

* Now use selection to extract the area containing the first 2 months of temperature data for the first 3 years, `albany[:3,1:3]`.

* Then try `albany[:3][1:3]`.

What do you find?

Why is it different? Why did it work for selecting one item?

* What would you need to put in the second set of brackets to get the same result? Try this out.

In [107]:
albany[:3,1:3]

array([[22.1, 22.8],
       [20.1, 22.2],
       [20.2, 22.1]])

In [108]:
albany[:3][1:3]

array([[1881. ,   20.1,   22.2,   22.2,   19.6,   17.1,   14.4,   15.3,
          15.5,   16.4,   16.1,   18.7,   20.7,   18.2],
       [1882. ,   20.2,   22.1,   20.1,   18.8,   16.3,   14.6,   14.4,
          14.9,   16.4,   17.3,   17.8,   20.8,   17.8]])

In [110]:
albany[:3][:,1:3]

array([[22.1, 22.8],
       [20.1, 22.2],
       [20.2, 22.1]])

#### Specifying an axis

Lets say we want to print the maximim temperatures for the first four years.

If we try
```
print(albany[0:4,1:].max())
```
what do we get?

`ndarray.max()` (see also `numpy.amax()`) is an example of a method that can be applied to different _axes_ of the array.

* Use the `axis` argument to print the maximum temperatures for Albany for the first 4 years.

In [45]:
print(albany[0:4,1:].max())


22.8


In [115]:
np.max(albany[0:4,1:], axis = 1)

array([22.8, 22.2, 22.1, 21.9])

In [113]:
print(albany[0:4,1:])

[[22.1 22.8 20.6 19.2 17.5 14.7 15.1 15.2 16.2 16.2 18.  20.8 18.2]
 [20.1 22.2 22.2 19.6 17.1 14.4 15.3 15.5 16.4 16.1 18.7 20.7 18.2]
 [20.2 22.1 20.1 18.8 16.3 14.6 14.4 14.9 16.4 17.3 17.8 20.8 17.8]
 [20.7 20.5 19.9 20.1 17.3 15.9 14.5 14.1 14.4 16.5 18.2 21.9 17.8]]


### Comparing the towns

* Write a method that, for each town, finds the decade with the largest difference between the highest and lowest temperatures. Your method should print out a table with the town, decade, highest temperature, lowest temperature and the difference.

Which town has the highest temperature difference overall?

* Repeat the above using the standard deviation of the temperatures.

Which town has the highest standard deviation in one decade?



In [116]:
def max_difference(my_table):
    start = my_table[0,0].astype(int)//10*10
    end = my_table[-1,0].astype(int)//10*10
    decade_array = np.arange(start,end,10)
    dif = 0
    decade = 0
    min_result = 0
    max_result = 0
    for i in decade_array:
        mask = np.logical_and(my_table[:,0]>= i,my_table[:,0]<i+10)
        my_array = my_table[mask]
        my_temp = my_array[:,1:-1]
        if my_temp.size != 0:
            my_min = np.nanmin(my_temp)
            my_max = np.nanmax(my_temp)
            difference = my_max - my_min
            if difference > dif:
                dif = difference
                decade = i
                min_result = my_min
                max_result = my_max
    return dif,decade,min_result,max_result
        

In [130]:
(towns,tables) = get_temperatures (STATIONS, quiet=True)
towns
for i in towns:
    my_table = tables[towns.index(i)]
    a,b,c,d = max_difference(my_table)
    print('Town: {town:<10} | Decade : {decade:<5} - {decade_2:<4}| Highest Temp: {high}| Lowest Temp: {low}| difference:{differ:0.2f}'.format(town = i, decade = b, decade_2 = b+10 ,high = d, low = c , differ = a))
    


Town: Albany     | Decade : 1890  - 1900| Highest Temp: 24.4| Lowest Temp: 12.4| difference:12.00
Town: Broome     | Decade : 1950  - 1960| Highest Temp: 36.4| Lowest Temp: 25.8| difference:10.60
Town: Geraldton  | Decade : 1880  - 1890| Highest Temp: 34.6| Lowest Temp: 17.8| difference:16.80
Town: Perth      | Decade : 1980  - 1990| Highest Temp: 36.3| Lowest Temp: 16.2| difference:20.10


In [126]:
def max_sd (my_table):
    start = my_table[0,0].astype(int)//10*10
    end = my_table[-1,0].astype(int)//10*10
    decade_array = np.arange(start,end,10)
    sd = 0
    decade = 0
    for i in decade_array:
        mask = np.logical_and(my_table[:,0]>= i,my_table[:,0]<i+10)
        my_array = my_table[mask]
        my_temp = my_array[:,1:-1]
        if my_temp.size != 0:
            my_sd = np.std(my_temp)
            if my_sd > sd:
                sd = my_sd
                decade = i
    return sd,decade

In [129]:
(towns,tables) = get_temperatures (STATIONS, quiet=True)
for i in towns:
    my_table = tables[towns.index(i)]
    a,b = max_sd(my_table)
    print('Town: {town:<10} | Decade : {decade:<5} - {decade_2:<4}| max_sd:{sd:0.2f}'.format(town = i, decade = b, decade_2 = b+10, sd = a))
    

Town: Albany     | Decade : 1950  - 1960| max_sd:2.96
Town: Broome     | Decade : 1950  - 1960| max_sd:2.37
Town: Geraldton  | Decade : 1880  - 1890| max_sd:4.18
Town: Perth      | Decade : 1970  - 1980| max_sd:5.32


In [35]:
a = [1,2,3,4,5,6]
b = a[:2]

for idx in range(len(b)):
    b[idx] += 10

print(a)
print(b)

[1, 2, 3, 4, 5, 6]
[11, 12]


In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 10

print(a)
print(b)

[11 12  3  4  5  6]
[11 12]


In [0]:
a = range(1,20)

In [37]:
a = [1,2,3,4,5,6]
b = a

for idx in range(len(b)):
    b[idx] += 10

print(a)
print(b)

[11, 12, 13, 14, 15, 16]
[11, 12, 13, 14, 15, 16]


In [32]:
a = [[1, 2, 3],[4, 5, 6]]
b = a[0]

b.append(100)

print(a)
print(b)

[[1, 2, 3, 100], [4, 5, 6]]
[1, 2, 3, 100]


In [3]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = a[0]
b += 10

print(a)
print(b)

[[11 12 13]
 [ 4  5  6]]
[11 12 13]


In [15]:
a = list(range(0,30))
b = slice(0,30,3)
a[b] == a[::3]

True

In [16]:
a = [12,23,23]
b = [100]
a+b

[12, 23, 23, 100]

In [118]:
bool(0)


False

In [16]:
a = np.array([[1,2,3,4],[2,3,4,5]])
a.sum(axis = 0)




array([3, 5, 7, 9])

In [122]:
a = ["3.4","3","0.8","ajd"]
b = [float(x) if x[0].isdigit() else float("Nan") for x in a]
def myfun(x):
    b = []
    for i in x:
        try:
            b.append(float(i))
        except:
            b.append(float("Nan"))
    return b
myfun(a)            
   

[3.4, 3.0, 0.8, nan]

In [125]:
x = "1.23d"
x[0].isdigit()

True

&copy; Cara MacNish